import logging

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError
from odoo.osv import expression

_logger = logging.getLogger(__name__)


class MailMessage(models.Model):
    _inherit = "mail.message"

    user_vote = fields.Integer(
        string="User Vote",
        default=0,
        help="Vote status given by the user. 0: No vote, 1: Upvoted, -1: Downvoted.",
    )

    @api.model
    def _message_fetch(
        self, domain, search_term=None, before=None, after=None, around=None, limit=30
    ):
        """Override to filter only LLM messages for llm.thread model.

        For LLM threads, we only want to display messages that have an llm_role
        (user, assistant, tool), not system notifications or other message types
        that would clutter the AI conversation interface.
        """
        # Check if this is for an llm.thread model
        is_llm_thread = any(
            condition[0] == "model"
            and condition[1] == "="
            and condition[2] == "llm.thread"
            for condition in domain
            if isinstance(condition, (list, tuple)) and len(condition) == 3
        )

        if is_llm_thread:
            # Add LLM role filter for LLM threads - only show messages with llm_role
            llm_role_filter = [("llm_role", "!=", False)]
            domain = expression.AND([domain, llm_role_filter])

        # Call parent method with modified domain
        return super()._message_fetch(domain, search_term, before, after, around, limit)

    def _extras_to_store(self, store, format_reply):
        """Add LLM-specific fields to the message store."""
        super()._extras_to_store(store, format_reply)

        for message in self:
            data = {}

            # Add LLM-specific fields
            if hasattr(message, "llm_role") and message.llm_role:
                data["llm_role"] = message.llm_role
                # Set is_note=True for LLM messages to get the right bubble style
                data["is_note"] = True

            if hasattr(message, "user_vote"):
                data["user_vote"] = message.user_vote

            if hasattr(message, "body_json") and message.body_json:
                data["body_json"] = message.body_json

            if data:  # Only add to store if we have data
                store.add(message, data)

    def set_user_vote(self, vote_value):
        """Sets the user vote on this message, performing validation checks."""
        self.ensure_one()
        if self.llm_role not in ("assistant", "tool"):
            raise UserError(
                _(
                    "Voting is only allowed on messages generated by the assistant or a tool."
                )
            )
        if not isinstance(vote_value, int) or vote_value not in [-1, 0, 1]:
            raise ValidationError(
                _(
                    "Invalid vote value. Must be an integer: 1 (up), -1 (down), or 0 (none)."
                )
            )
        self.sudo().write({"user_vote": vote_value})
