{
    'name': 'Trixo Product Label',
    'version': '19.0.2.0.0',
    'summary': 'Custom Product Labels for Trixocom',
    'description': '\n        This module adds custom product label formats:\n        - 2x7 with price\n        - 4x7 with price\n        - 4x12\n        - 4x12 with price\n        - 4xA4\n        - ZPL Labels\n    ',
    'author': 'Trixocom',
    'website': 'https://www.trixocom.com',
    'license': 'GPL-3',
    'category': 'Sales/Sales',
    'depends': ['product'],
    'data': ['data/report_url_data.xml', 'data/paperformat_data.xml', 'wizard/product_label_layout_views.xml', 'report/product_label_reports.xml'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
